name: Gerar Pac-Man do gráfico

on:
  schedule:
    - cron: '0 0 * * *' # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Gerar Pac-Man SVG
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: gdTech1
