name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: gdTech1
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light&color_snake=#D4AF37&color_dots=#E6D3A3,#CD7F32,#8B5E3C,#5C4033
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#D4AF37&color_dots=#E6D3A3,#CD7F32,#8B5E3C,#5C4033
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
